directories-root:
  - name: downloads
    original: Downloads
    destination: ~/
  - name: files
    original: Documents
    destination: ~/
  - name: images
    original: Pictures
    destination: ~/
  - name: music
    original: Music
    destination: ~/
  - name: public
    original: Public
    destination: ~/
  - name: templates
    original: Templates
    destination: ~/
  - name: videos
    original: Videos
    destination: ~/

dir-root-extra:
  - name: develop
    destination: ~/

dir-files:
  - name: books
    destination: ~/files
  - name: cadeiras
    destination: ~/files
  - name: notes
    destination: ~/files

dir-develop:
  - name: notas
    destination: ~/develop
  - name: ufpe
    destination: ~/develop
  - name: projetos
    destination: ~/develop
  - name: archive
    destination: ~/develop
