portable: 
  - nome: gh
    url: https://github.com/cli/cli/releases/download/v2.63.0/gh_2.63.0_linux_amd64.tar.gz
  - nome: glab
    url: https://gitlab.com/gitlab-org/cli/-/releases/v1.112.0/downloads/glab_1.112.0_linux_amd64.tar.gz
  - nome: 
    url: 
  - nome: 
    url: 

system:
  - nome: git
    url: 
  - nome: gcc
    url: 

containers:
  - nome: ubuntu-dev
